name: Android CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    env:
      SIGNING_KEYSTORE_BASE64: ${{ secrets.SIGNING_KEYSTORE_BASE64 }}
      SIGNING_KEY_ALIAS: ${{ secrets.SIGNING_KEY_ALIAS }}
      SIGNING_KEY_PASSWORD: ${{ secrets.SIGNING_KEY_PASSWORD }}
      SIGNING_STORE_PASSWORD: ${{ secrets.SIGNING_STORE_PASSWORD }}

    steps:
    - uses: actions/checkout@v7
    - name: set up JDK 17
      uses: actions/setup-java@v6
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Setup Gradle & Build Cache
      uses: gradle/actions/setup-gradle@v6

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Setup Keystore & Signing Config
      if: ${{ env.SIGNING_KEYSTORE_BASE64 != '' }}
      run: |
        mkdir -p .sign
        echo "$SIGNING_KEYSTORE_BASE64" | base64 -d > .sign/keystore.jks
        echo "keystore=.sign/keystore.jks" > .sign/dsu_sideloader.prop
        echo "keystore_pw=$SIGNING_STORE_PASSWORD" >> .sign/dsu_sideloader.prop
        echo "alias=$SIGNING_KEY_ALIAS" >> .sign/dsu_sideloader.prop
        echo "alias_pw=$SIGNING_KEY_PASSWORD" >> .sign/dsu_sideloader.prop

    - name: Build with Gradle
      env:
        SIGNING_KEYSTORE_PATH: .sign/keystore.jks
      run: |
        if [ -f ".sign/keystore.jks" ]; then
          ./gradlew assembleRelease assembleMiniDebug
        else
          ./gradlew assembleMiniDebug
        fi

    - name: Archive release artifacts
      uses: actions/upload-artifact@v7
      with:
        name: outputs-apk-release
        path: app/build/outputs/apk/release
        if-no-files-found: ignore

    - name: Archive miniDebug artifacts
      uses: actions/upload-artifact@v7
      with:
        name: outputs-apk-minidebug
        path: app/build/outputs/apk/miniDebug
        if-no-files-found: ignore
